#!/bin/bash

#--------------------------------------------------------------------
# (c) Koen Hufkens for BlueGreen Labs (BV)
#
# This script installs all necessary configuration
# files as required to upload images to the PhenoCam server
# (phenocam.nau.edu) on your NetCam Live2 camera REMOTELY with
# minimum interaction with the camera.
#
# Use is permitted within the context of the PhenoCam US network,
# in its standard configuration. For all exceptions contact
# BlueGreen Labs
#
#--------------------------------------------------------------------

#---- global login banner ----

echo ""
echo "===================================================================="
echo ""
echo " Phenocam Installation Tool (PIT) V2 for NetCam Live2 cameras"
echo ""
echo " (c) BlueGreen Labs (BV) 2024 - https://bluegreenlabs.org"
echo ""
echo " -----------------------------------------------------------"
echo ""

#---- subroutines ----

# error handling installation subroutines
error_exit(){
  echo ""
  echo " NOTE: If no confirmation of a successful upload is provided,"
  echo " or warnings are shown, check all script parameters."
  echo ""
  echo "===================================================================="
  exit 0
}

# error handling key retrieval routine
error_key(){
  echo ""
  echo " WARNING: No login key (pair) 'phenocam_key' found... "
  echo " (please run the installation routine)"
  echo ""
  echo "===================================================================="
  exit 0
}

# error handling purging routine
error_purge(){
  echo ""
  echo " WARNING: Purging of system settings failed, please try again!"
  echo ""
  echo "===================================================================="
  exit 0
}

# error handling test routine
error_upload(){
  echo ""
  echo " WARNING: Image upload failed, check your network connection"
  echo " and settings!"
  echo ""
  echo "===================================================================="
  exit 0
}

# define usage
usage() { 
 echo "
 
 This scripts covers the installation of your
 Stardot NetCam Live2 PhenoCam
 please use the following arguments.
 
 Arguments which require an additional parameter
 have descriptions enclosed in <> brackets. Other
 arguments are binary choices.
 
 Usage: $0
  [-i <camera ip address>]
  [-p <camera password>]
  [-n <camera name>]
  [-o <time offset from UTC/GMT>]
  [-s <start time 0-23>]
  [-e <end time 0-23>]  
  [-m <interval minutes>]
  [-k key based (sFTP) authentication if specified]
  [-u uploads images if specified, requires -i to be specified]
  [-r retrieves login key if specified, requires -i to be specified]
  [-x purges all previous settings and keys if specified, requires -i to be specified]
  [-h calls this menu if specified]
  " 1>&2
  
  exit 0
 }

upload() {
 echo " Try to upload image to the server"
 echo ""
 
  # check if IP is provided
 if [ -z ${ip} ]; then
  echo " No IP address provided"
  error_upload
 fi
 
 # create command
 command="
  sh /mnt/cfg1/scripts/phenocam_upload.sh
 "
 
 # execute command
 ssh admin@${ip} ${command} || error_upload 2>/dev/null
 
 echo " -----------------------------------------------------------"
 echo ""
 echo " Done, successfully uploaded images"
 echo ""
 echo "===================================================================="
 exit 0
 }

# if the retrieve the public key
retrieve() {
 
 # check if IP is provided
 if [ -z ${ip} ]; then
  echo " No IP address provided"
  error_key
 fi
 
 # create command
 command="
  if [ -f '/mnt/cfg1/phenocam_key' ]; then dropbearkey -t rsa -f /mnt/cfg1/phenocam_key -y; else exit 1; fi
 "

 echo " Retrieving the public key login credentials"
 echo ""
 
 # execute command
 ssh admin@${ip} ${command} > tmp.pub || error_key 2>/dev/null
 
 # strip out the public key
 # no header or footer
 grep "ssh-rsa" tmp.pub > phenocam_key.pub
 rm -rf tmp.pub
 
 echo "" 
 echo " The public key was written to the 'phenocam_key.pub' file"
 echo " in your current working directory!"
 echo ""
 echo " Forward this file to phenocam@nau.edu to finalize your"
 echo " sFTP installation."
 echo ""
 echo "===================================================================="
 exit 0
}

# if the retrieve argument is active retrieve the
# public private keys, check if there are more than
# two arguments given to avoid accidental purging
purge() {

 echo " Purging all previous settings and login credentials"
 echo ""
 
  # check if IP is provided
 if [ -z ${ip} ]; then
  echo " No IP address provided"
  error_purge
 fi
 
 # ASK FOR CONFIRMATION!!!
 read -p "Do you wish to perform this action?" yesno
 case $yesno in
        [Yy]* ) 
            echo "Purging the system settings..."
        ;;
        [Nn]* ) 
            echo "You answered no, exiting"
            exit_purge
        ;;
        * ) 
            exit_purge
        ;;
 esac 
 
 # create command
 command="
  rm -rf /mnt/cfg1/settings.txt
  rm -rf /mnt/cfg1/.password
  rm -rf /mnt/cfg1/phenocam_key
  rm -rf /mnt/cfg1/update.txt
  rm -rf /mnt/cfg1/scripts/
 "
 
 # execute command
 ssh admin@${ip} ${command} || error_purge 2>/dev/null
 
 echo ""
 echo " Done, cleaned the camera settings!"
 echo ""
 echo "===================================================================="
 exit 0
}

#---- parse arguments (and/or execute subroutine calls) ----

# grab arguments
while getopts "hi:p:n:o:s:e:m:kurx" option;
do
    case "${option}"
        in
        i) ip=${OPTARG} ;;
        p) pass=${OPTARG} ;;
        n) name=${OPTARG} ;;
        o) offset=${OPTARG} ;;
        s) start=${OPTARG} ;;
        e) end=${OPTARG} ;;
        m) int=${OPTARG} ;;
        k) key=TRUE ;;
        u) upload ;;
        r) retrieve ;;
        x) purge ;;
        h | *) usage; exit 0 ;;
    esac
done

#---- installation routine ----

# validating parameters
if [[ -z ${ip} || ${ip} == -* ]]; then
 echo " WARNING: No IP address provided"
 error_exit
fi

if [[ -z ${pass} || ${pass} == -* ]]; then
 echo " WARNING: No password provided"
 error_exit
fi

if [[ -z ${name} || ${name} == -* ]]; then
 echo " WARNING: No camera name provided"
 error_exit
fi

if [[ -z ${offset} || ${offset} == -* ]]; then
 echo " WARNING: No GMT time offset provided"
 error_exit
fi

if [[ -z ${start} || ${start} == -* ]]; then
 echo " NOTE: No start time (24h format) provided, using the default (9h)"
 start='9'
fi

if [[ -z ${end} || ${end} == -* ]]; then
 echo " NOTE: No end time (24h format) provided, using the default (22h)"
 end='22'
fi

if [[ -z ${int} || ${int} == -* ]]; then
 echo " NOTE: No interval (in minutes) provided, using the default (30 min)"
 int='30'
fi

if [ "${key}" ]; then
  # print the content of the path to the
  # key and assign to a variable
  echo " NOTE: Using secure SFTP and key based logins!"
  echo ""
  has_key="TRUE"
 else
  echo " NOTE: No key will be generated, defaulting to insecure FTP!"
  echo ""
  has_key="FALSE"
fi

# Default to GMT time zone
tz="GMT"

# colour settings
red="220"
green="125"
blue="220"
brightness="128"
contrast="128"
sharpness="128"
hue="128"
saturation="100"
backlight="0"

command="
 echo TRUE > /mnt/cfg1/update.txt &&
 echo ${name} > /mnt/cfg1/settings.txt &&
 echo ${offset} >> /mnt/cfg1/settings.txt &&
 echo ${tz} >> /mnt/cfg1/settings.txt &&
 echo ${start} >> /mnt/cfg1/settings.txt &&
 echo ${end} >> /mnt/cfg1/settings.txt &&
 echo ${int} >> /mnt/cfg1/settings.txt &&
 echo ${red} >> /mnt/cfg1/settings.txt &&
 echo ${green} >> /mnt/cfg1/settings.txt &&
 echo ${blue} >> /mnt/cfg1/settings.txt &&
 echo ${brightness} >> /mnt/cfg1/settings.txt &&
 echo ${sharpness} >> /mnt/cfg1/settings.txt &&
 echo ${hue} >> /mnt/cfg1/settings.txt &&
 echo ${contrast} >> /mnt/cfg1/settings.txt &&
 echo ${saturation} >> /mnt/cfg1/settings.txt &&
 echo ${backlight} >> /mnt/cfg1/settings.txt &&
 echo ${pass} > /mnt/cfg1/.password &&
 if [[ ${has_key} && ! -f /mnt/cfg1/phenocam_key ]]; then dropbearkey -t rsa -f /mnt/cfg1/phenocam_key >/dev/null; fi &&
 cd /var/tmp; cat | base64 -d | tar -x &&
 if [ ! -d '/mnt/cfg1/scripts' ]; then mkdir /mnt/cfg1/scripts; fi && 
 cp /var/tmp/files/* /mnt/cfg1/scripts &&
 rm -rf /var/tmp/files &&
 sh /mnt/cfg1/scripts/check_firmware.sh &&
 echo '#!/bin/sh' > /mnt/cfg1/userboot.sh &&
 echo 'sh /mnt/cfg1/scripts/phenocam_install.sh' >> /mnt/cfg1/userboot.sh &&
 echo 'sh /mnt/cfg1/scripts/phenocam_upload.sh' >> /mnt/cfg1/userboot.sh &&
 echo '' &&
 echo ' Successfully uploaded install instructions.' &&
 echo ' The camera configuration will take effect on reboot.' &&
 echo '' &&
 echo ' The following options have been set:' &&
 echo ' ------------------------------------' &&
 echo '' &&
 echo ' Sitename: ${name} | Timezone: GMT${offset}' &&
 echo ' Upload start - end: ${start} - ${end} (h)' &&
 echo ' Upload interval: every ${int} (min)' &&
 echo '' &&
 echo ' And the following colour settings:' &&
 echo ' ----------------------------------' &&
 echo '' &&
 echo ' Gain values (R G B): ${red} ${green} ${blue}' &&
 echo ' Brightness: ${brightness} | Sharpness: ${sharpness}' &&
 echo ' Hue: ${hue} | Contrast: ${contrast}' &&
 echo ' Saturation: ${saturation} | Backlight: ${backlight}' &&
 echo '' &&
 if [ -f /mnt/cfg1/phenocam_key ]; then echo ' ----------------------------------'; fi &&
 echo '' &&
 if [ -f /mnt/cfg1/phenocam_key ]; then echo ' A key (pair) exists or was generated, please run:'; fi &&
 if [ -f /mnt/cfg1/phenocam_key ]; then echo ' ./PIT.sh ${ip} -r'; fi &&
 if [ -f /mnt/cfg1/phenocam_key ]; then echo ' to display/retrieve the current login key'; fi &&
 echo '' &&
 echo '====================================================================' &&
 echo '' &&
 echo ' --> SUCCESSFUL UPLOAD OF THE INSTALLATION SCRIPT   <-- ' &&
 echo ' --> THE CAMERA WILL REBOOT TO COMPLETE THE INSTALL <--' &&
 echo '' &&
 echo ' [NOTE: the full install will take several reboot cycles (~5 min !!),' && 
 echo ' please wait before logging in or triggering the script again. The' &&
 echo ' current SSH connection will be closed for reboot in 30 sec.]' &&
 echo '' &&
 echo '====================================================================' &&
 echo '' &&
 sh /mnt/cfg1/scripts/reboot_camera.sh
"

echo ""
echo " Please login to execute the installation script."
echo ""


# install command
BINLINE=$(awk '/^__BINARY__/ { print NR + 1; exit 0; }' $0)
tail -n +${BINLINE} $0 | ssh admin@${ip} ${command} || error_exit 2>/dev/null

#---- purge password from history ----

# remove last lines from history
# containing the password
history -d -1--2

# exit
exit 0

__BINARY__
ZmlsZXMvY2hlY2tfZmlybXdhcmUuc2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAwMDA2NjQAMDAwMTc1
MAAwMDAxNzUwADAwMDAwMDAyMDMwADE0NjU3NjA1MTc1ADAxNTcyMAAgMAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1c3RhciAgAGtodWZrZW5zAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAa2h1ZmtlbnMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAj
IS9iaW4vc2gKCiMtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLQojIChjKSBLb2VuIEh1ZmtlbnMgZm9yIEJsdWVHcmVlbiBM
YWJzIChCVikKIwojIFVuYXV0aG9yaXplZCBjaGFuZ2VzIHRvIHRoaXMgc2NyaXB0IGFyZSBjb25z
aWRlcmVkIGEgY29weXJpZ2h0CiMgdmlvbGF0aW9uIGFuZCB3aWxsIGJlIHByb3NlY3V0ZWQuCiMK
Iy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tCgojIGhhcmQgY29kZSBwYXRoIHdoaWNoIGFyZSBsb3N0IGluIHNvbWUgaW5z
dGFuY2VzCiMgd2hlbiBjYWxsaW5nIHRoZSBzY3JpcHQgdGhyb3VnaCBzc2ggClBBVEg9Ii91c3Iv
bG9jYWwvYmluOi91c3IvbG9jYWwvc2JpbjovdXNyL2JpbjovdXNyL3NiaW46L2Jpbjovc2JpbiIK
CiMgZ3JhYiBwYXNzd29yZApwYXNzPWBhd2sgJ05SPT0xJyAvbW50L2NmZzEvLnBhc3N3b3JkYAoK
IyBtb3ZlIGludG8gdGVtcG9yYXJ5IGRpcmVjdG9yeQpjZCAvdmFyL3RtcAoKIyBkdW1wIGRldmlj
ZSBpbmZvCndnZXQgaHR0cDovL2FkbWluOiR7cGFzc31AMTI3LjAuMC4xL3ZiLmh0bT9EZXZpY2VJ
bmZvICY+L2Rldi9udWxsCgojIGV4dHJhY3QgZmlybXdhcmUgdmVyc2lvbgp2ZXJzaW9uPWBjYXQg
dmIuaHRtP0RldmljZUluZm8gfCBjdXQgLWQnLScgLWYzIHwgY3V0IC1kICcgJyAtZjEgfCB0ciAt
ZCAnQicgYAoKIyBjbGVhbiB1cCBkZXRyaXR1cwpybSB2YioKCmlmIFtbICR2ZXJzaW9uIC1sdCA5
MTA4IF1dOyB0aGVuCgogIyBlcnJvciBzdGF0ZW1lbnQgKyB0cmlnZ2VyaW5nCiAjIHRoZSBzc2gg
ZXJyb3Igc3VmZml4CiBlY2hvICIgV0FSTklORzogeW91ciBmaXJtd2FyZSB2ZXJzaW9uICR2ZXJz
aW9uIGlzIG5vdCBzdXBwb3J0ZWQsIgogZWNobyAiIHBsZWFzZSB1cGRhdGUgeW91ciBjYW1lcmEg
ZmlybXdhcmUgdG8gdmVyc2lvbiBCOTEwOCBvciBsYXRlci4iCiBleGl0IDEKCmVsc2UKIAogIyBj
bGVhbiBleGl0CiBleGl0IDAKZmkKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmaWxl
cy9jaGxzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDAwMDc3NQAwMDAxNzUwADAw
MDE3NTAAMDAwMDAwMDA3NDQAMTQ1NjIxNTA0NTcAMDEzMjc1ACAwAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHVzdGFyICAAa2h1ZmtlbnMAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAABraHVma2VucwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMhL2Jp
bi9zaAoKIy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tCiMgKGMpIEtvZW4gSHVma2VucyBmb3IgQmx1ZUdyZWVuIExhYnMg
KEJWKQojCiMgVW5hdXRob3JpemVkIGNoYW5nZXMgdG8gdGhpcyBzY3JpcHQgYXJlIGNvbnNpZGVy
ZWQgYSBjb3B5cmlnaHQKIyB2aW9sYXRpb24gYW5kIHdpbGwgYmUgcHJvc2VjdXRlZC4KIwojLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0KCm5yc2VydmVycz1gYXdrICdFTkQge3ByaW50IE5SfScgL21udC9jZmcxL3NlcnZl
ci50eHRgCmFsbD0ibmF1IgptYXRjaD1gZ3JlcCAtRSAke2FsbH0gL21udC9jZmcxL3NlcnZlci50
eHQgfCB3YyAtbGAKCmlmIFsgJHtucnNlcnZlcnN9IC1lcSAke21hdGNofSBdOwp0aGVuCiBlY2hv
ICJuZXR3b3JrPXBoZW5vY2FtIgpmaQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZmlsZXMv
cGhlbm9jYW1faW5zdGFsbC5zaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAwMDA3NTUAMDAwMTc1MAAwMDAx
NzUwADAwMDAwMDEyNDU1ADE0NjU3NTc2NjUxADAxNjMxMgAgMAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1c3RhciAgAGtodWZrZW5zAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAa2h1ZmtlbnMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjIS9iaW4v
c2gKCiMtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLQojIChjKSBLb2VuIEh1ZmtlbnMgZm9yIEJsdWVHcmVlbiBMYWJzIChC
VikKIwojIFVuYXV0aG9yaXplZCBjaGFuZ2VzIHRvIHRoaXMgc2NyaXB0IGFyZSBjb25zaWRlcmVk
IGEgY29weXJpZ2h0CiMgdmlvbGF0aW9uIGFuZCB3aWxsIGJlIHByb3NlY3V0ZWQuCiMKIy0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tCgojIGhhcmQgY29kZSBwYXRoIHdoaWNoIGFyZSBsb3N0IGluIHNvbWUgaW5zdGFuY2Vz
CiMgd2hlbiBjYWxsaW5nIHRoZSBzY3JpcHQgdGhyb3VnaCBzc2ggClBBVEg9Ii91c3IvbG9jYWwv
YmluOi91c3IvbG9jYWwvc2JpbjovdXNyL2JpbjovdXNyL3NiaW46L2Jpbjovc2JpbiIKCnNsZWVw
IDMwCmNkIC92YXIvdG1wCgojIHVwZGF0ZSBwZXJtaXNzaW9ucyBzY3JpcHRzCmNobW9kIGErcnd4
IC9tbnQvY2ZnMS9zY3JpcHRzLyoKCiMgZ2V0IHRvZGF5cyBkYXRlCnRvZGF5PWBkYXRlICsiJVkg
JW0gJWQgJUg6JU06JVMiYAoKIyBzZXQgY2FtZXJhIG1vZGVsIG5hbWUKbW9kZWw9Ik5ldENhbSBM
aXZlMiIKCiMgdXBsb2FkIC8gZG93bmxvYWQgc2VydmVyIC0gbG9jYXRpb24gZnJvbSB3aGljaCB0
byBncmFiIGFuZAojIGFuZCB3aGVyZSB0byBwdXQgY29uZmlnIGZpbGVzCmhvc3Q9J3BoZW5vY2Ft
Lm5hdS5lZHUnCgojIGNyZWF0ZSBkZWZhdWx0IHNlcnZlcgppZiBbICEgLWYgJy9tbnQvY2ZnMS9z
ZXJ2ZXIudHh0JyBdOyB0aGVuCiAgZWNobyAke2hvc3R9ID4gL21udC9jZmcxL3NlcnZlci50eHQK
ICBlY2hvICJ1c2luZyBkZWZhdWx0IGhvc3Q6ICR7aG9zdH0iID4+IC92YXIvdG1wL2luc3RhbGxf
bG9nLnR4dAogIGNobW9kIGErcncgL21udC9jZmcxL3NlcnZlci50eHQKZmkKCiMgT25seSB1cGRh
dGUgdGhlIHNldHRpbmdzIGlmIGV4cGxpY2l0bHkKIyBpbnN0cnVjdGVkIHRvIGRvIHNvLCB0aGlz
IGZpbGUgd2lsbCBiZQojIHNldCB0byBUUlVFIGJ5IHRoZSBQSVQuc2ggc2NyaXB0LCB3aGljaAoj
IHVwb24gcmVib290IHdpbGwgdGhlbiBiZSBydW4uCgppZiBbIGBjYXQgL21udC9jZmcxL3VwZGF0
ZS50eHRgID0gIlRSVUUiIF07IHRoZW4gCgoJIyBzdGFydCBsb2dnaW5nCgllY2hvICItLS0tLSAk
e3RvZGF5fSAtLS0tLSIgPj4gL3Zhci90bXAvaW5zdGFsbF9sb2cudHh0CgoJIy0tLS0tIHJlYWQg
aW4gc2V0dGluZ3MKCWlmIFsgLWYgJy9tbnQvY2ZnMS9zZXR0aW5ncy50eHQnIF07IHRoZW4KCSBj
YW1lcmE9YGF3ayAnTlI9PTEnIC9tbnQvY2ZnMS9zZXR0aW5ncy50eHRgCgkgdGltZV9vZmZzZXQ9
YGF3ayAnTlI9PTInIC9tbnQvY2ZnMS9zZXR0aW5ncy50eHRgCgkgY3Jvbl9zdGFydD1gYXdrICdO
Uj09NCcgL21udC9jZmcxL3NldHRpbmdzLnR4dGAKCSBjcm9uX2VuZD1gYXdrICdOUj09NScgL21u
dC9jZmcxL3NldHRpbmdzLnR4dGAKCSBjcm9uX2ludD1gYXdrICdOUj09NicgL21udC9jZmcxL3Nl
dHRpbmdzLnR4dGAKCSAKCSAjIGNvbG91ciBiYWxhbmNlCiAJIHJlZD1gYXdrICdOUj09NycgL21u
dC9jZmcxL3NldHRpbmdzLnR4dGAKCSBncmVlbj1gYXdrICdOUj09OCcgL21udC9jZmcxL3NldHRp
bmdzLnR4dGAKCSBibHVlPWBhd2sgJ05SPT05JyAvbW50L2NmZzEvc2V0dGluZ3MudHh0YAoJIAoJ
ICMgcmVhZCBpbiB0aGUgYnJpZ2h0bmVzcy9zaGFycG5lc3MvaHVlL3NhdHVyYXRpb24gdmFsdWVz
CgkgYnJpZ2h0bmVzcz1gYXdrICdOUj09MTAnIC9tbnQvY2ZnMS9zZXR0aW5ncy50eHRgCgkgc2hh
cnBuZXNzPWBhd2sgJ05SPT0xMScgL21udC9jZmcxL3NldHRpbmdzLnR4dGAKCSBodWU9YGF3ayAn
TlI9PTEyJyAvbW50L2NmZzEvc2V0dGluZ3MudHh0YAoJIGNvbnRyYXN0PWBhd2sgJ05SPT0xMycg
L21udC9jZmcxL3NldHRpbmdzLnR4dGAJIAoJIHNhdHVyYXRpb249YGF3ayAnTlI9PTE0JyAvbW50
L2NmZzEvc2V0dGluZ3MudHh0YAoJIGJsYz1gYXdrICdOUj09MTUnIC9tbnQvY2ZnMS9zZXR0aW5n
cy50eHRgCgllbHNlCgkgZWNobyAiU2V0dGluZ3MgZmlsZSBtaXNzaW5nLCBhYm9ydGluZyBpbnN0
YWxsIHJvdXRpbmUhIiA+PiAvdmFyL3RtcC9pbnN0YWxsX2xvZy50eHQKCWZpCgkKICAgICAgICBw
YXNzPWBhd2sgJ05SPT0xJyAvbW50L2NmZzEvLnBhc3N3b3JkYAoKCSMtLS0tLSBzZXQgdGltZSB6
b25lIG9mZnNldCAoZnJvbSBHTVQpCgkKCSMgc2V0IHNpZ24gdGltZSB6b25lCglTSUdOPWBlY2hv
ICR7dGltZV9vZmZzZXR9IHwgY3V0IC1jJzEnYAoKCSMgbm90ZSB0aGUgd2VpcmQgZmxpcCBpbiB0
aGUgbmV0Y2FtIGNhbWVyYXMKCWlmIFsgIiRTSUdOIiA9ICIrIiBdOyB0aGVuCgkgVFo9YGVjaG8g
IkdNVCR7dGltZV9vZmZzZXR9IiB8IHNlZCAncy8rLyUyRC9nJ2AKCWVsc2UKCSBUWj1gZWNobyAi
R01UJHt0aW1lX29mZnNldH0iIHwgc2VkICdzLy0vJTJCL2cnYAoJZmkKCgkjIGNhbGwgQVBJIHRv
IHNldCB0aGUgdGltZSAKCXdnZXQgaHR0cDovL2FkbWluOiR7cGFzc31AMTI3LjAuMC4xL3ZiLmh0
bT90aW1lem9uZT0ke1RafQoJCgkjIGNsZWFuIHVwIGRldHJpdHVzCglybSB2YioKCQoJZWNobyAi
dGltZSBzZXQgdG8gKGFzY2lpIGZvcm1hdCk6ICR7VFp9IiA+PiAvdmFyL3RtcC9pbnN0YWxsX2xv
Zy50eHQKCQoJIy0tLS0tIHNldCBvdmVybGF5CgkKCSMgY29udmVydCB0byBhc2NpaQoJaWYgWyAi
JFNJR04iID0gIisiIF07IHRoZW4KCSB0aW1lX29mZnNldD1gZWNobyAiJHt0aW1lX29mZnNldH0i
IHwgc2VkICdzLysvJTJCL2cnYAoJZWxzZQoJIHRpbWVfb2Zmc2V0PWBlY2hvICIke3RpbWVfb2Zm
c2V0fSIgfCBzZWQgJ3MvLS8lMkQvZydgCglmaQoJCgkjIG92ZXJsYXkgdGV4dAoJb3ZlcmxheV90
ZXh0PWBlY2hvICIke2NhbWVyYX0gLSAke21vZGVsfSAtICVhICViICVkICVZICVIOiVNOiVTIC0g
R01UJHt0aW1lX29mZnNldH0iIHwgc2VkICdzLyAvJTIwL2cnYAoJCgkjIGZvciBub3cgZGlzYWJs
ZSB0aGUgb3ZlcmxheQoJd2dldCBodHRwOi8vYWRtaW46JHtwYXNzfUAxMjcuMC4wLjEvdmIuaHRt
P292ZXJsYXl0ZXh0MT0ke292ZXJsYXlfdGV4dH0KCQoJIyBjbGVhbiB1cCBkZXRyaXR1cwoJcm0g
dmIqCgkKCWVjaG8gImhlYWRlciBzZXQgdG86ICR7b3ZlcmxheV90ZXh0fSIgPj4gL3Zhci90bXAv
aW5zdGFsbF9sb2cudHh0CgkKCSMtLS0tLSBzZXQgY29sb3VyIHNldHRpbmdzCgkKCSMgY2FsbCBB
UEkgdG8gc2V0IHRoZSB0aW1lIAoJd2dldCBodHRwOi8vYWRtaW46JHtwYXNzfUAxMjcuMC4wLjEv
dmIuaHRtP2JyaWdodG5lc3M9JHticmlnaHRuZXNzfQoJd2dldCBodHRwOi8vYWRtaW46JHtwYXNz
fUAxMjcuMC4wLjEvdmIuaHRtP2NvbnRyYXN0PSR7Y29udHJhc3R9Cgl3Z2V0IGh0dHA6Ly9hZG1p
bjoke3Bhc3N9QDEyNy4wLjAuMS92Yi5odG0/c2hhcnBuZXNzPSR7c2hhcnBuZXNzfQoJd2dldCBo
dHRwOi8vYWRtaW46JHtwYXNzfUAxMjcuMC4wLjEvdmIuaHRtP2h1ZT0ke2h1ZX0KCXdnZXQgaHR0
cDovL2FkbWluOiR7cGFzc31AMTI3LjAuMC4xL3ZiLmh0bT9zYXR1cmF0aW9uPSR7c2F0dXJhdGlv
bn0KCQoJIyBjbGVhbiB1cCBkZXRyaXR1cwoJcm0gdmIqCgkJCgkjIHNldCBSR0IgYmFsYW5jZQoJ
L3Vzci9zYmluL3NldF9yZ2Iuc2ggMCAke3JlZH0gJHtncmVlbn0gJHtibHVlfQoKCSMtLS0tLSBn
ZW5lcmF0ZSByYW5kb20gbnVtYmVyIGJldHdlZW4gMCBhbmQgdGhlIGludGVydmFsIHZhbHVlCgly
bnVtYmVyPWBhd2sgLXYgbWluPTAgLXYgbWF4PSR7Y3Jvbl9pbnR9ICdCRUdJTntzcmFuZCgpOyBw
cmludCBpbnQobWluK3JhbmQoKSoobWF4LW1pbisxKSl9J2AKCQoJIyBkaXZpZGUgNjAgbWluIGJ5
IHRoZSBpbnRlcnZhbAoJZGl2PWBhd2sgLXYgaW50ZXJ2YWw9JHtjcm9uX2ludH0gJ0JFR0lOIHtw
cmludCA1OS9pbnRlcnZhbH0nYAoJaW50PWBlY2hvICRkaXYgfCBjdXQgLWQnLicgLWYxYAoJCgkj
IGdlbmVyYXRlIGxpc3Qgb2YgdmFsdWVzIHRvIGl0ZXJhdGUgb3ZlcgoJdmFsdWVzPWBhd2sgLXYg
bWF4PSR7aW50fSAnQkVHSU57IGZvcihpPTA7aTw9bWF4O2krKykgcHJpbnQgaX0nYAoJCglmb3Ig
aSBpbiAke3ZhbHVlc307IGRvCgkgcHJvZHVjdD1gYXdrIC12IGludGVydmFsPSR7Y3Jvbl9pbnR9
IC12IHN0ZXA9JHtpfSAnQkVHSU4ge3ByaW50IGludChpbnRlcnZhbCpzdGVwKX0nYAkKCSBzdW09
YGF3ayAtdiBwcm9kdWN0PSR7cHJvZHVjdH0gLXYgbnI9JHtybnVtYmVyfSAnQkVHSU4ge3ByaW50
IGludChwcm9kdWN0K25yKX0nYAoJIAoJIGlmIFsgIiR7aX0iIC1lcSAiMCIgXTt0aGVuCgkgIGlu
dGVydmFsPWBlY2hvICR7c3VtfWAKCSBlbHNlCgkgIGlmIFsgIiRzdW0iIC1sZSAiNTkiIF07dGhl
bgoJICAgaW50ZXJ2YWw9YGVjaG8gJHtpbnRlcnZhbH0sJHtzdW19YAoJICBmaQoJIGZpCglkb25l
CgoJZWNobyAiY3JvbnRhYiBpbnRlcnZhbHMgc2V0IHRvOiAke2ludGVydmFsfSIgPj4gL3Zhci90
bXAvaW5zdGFsbF9sb2cudHh0CgoJIy0tLS0tIHNldCByb290IGNyb24gam9icwoJCgkjIHNldCB0
aGUgbWFpbiBwaWN0dXJlIHRha2luZyByb3V0aW5lCgllY2hvICIke2ludGVydmFsfSAke2Nyb25f
c3RhcnR9LSR7Y3Jvbl9lbmR9ICogKiAqIHNoIC9tbnQvY2ZnMS9zY3JpcHRzL3BoZW5vY2FtX3Vw
bG9hZC5zaCIgPiAvbW50L2NmZzEvc2NoZWR1bGUvYWRtaW4KCQkKCSMgdXBsb2FkIGlwIGFkZHJl
c3MgaW5mbyBhdCBtaWRkYXkKCWVjaG8gIjU5IDExICogKiAqIHNoIC9tbnQvY2ZnMS9zY3JpcHRz
L3BoZW5vY2FtX2lwX3RhYmxlLnNoIiA+PiAvbW50L2NmZzEvc2NoZWR1bGUvYWRtaW4KCQkKCSMg
cmVib290IGF0IG1pZG5pZ2h0IG9uIHJvb3QgYWNjb3VudAoJZWNobyAiNTkgMjMgKiAqICogc2gg
L21udC9jZmcxL3NjcmlwdHMvcmVib290X2NhbWVyYS5zaCIgPiAvbW50L2NmZzEvc2NoZWR1bGUv
cm9vdAoJCgkjIGluZm8KCWVjaG8gIkZpbmlzaGVkIGluaXRpYWwgc2V0dXAiID4+IC92YXIvdG1w
L2luc3RhbGxfbG9nLnR4dAoKCSMtLS0tLSBmaW5hbGl6ZSB0aGUgc2V0dXAgKyByZWJvb3QKCgkj
IHVwZGF0ZSB0aGUgc3RhdGUgb2YgdGhlIHVwZGF0ZSByZXF1aXJlbWVudAoJIyBpLmUuIHNraXAg
aWYgY2FsbGVkIG1vcmUgdGhhbiBvbmNlLCB1bmxlc3MKCSMgdGhpcyBmaWxlIGlzIG1hbnVhbGx5
IHNldCB0byBUUlVFIHdoaWNoCgkjIHdvdWxkIHJlcnVuIHRoZSBpbnN0YWxsIHJvdXRpbmUgdXBv
biByZWJvb3QKCWVjaG8gIkZBTFNFIiA+IC9tbnQvY2ZnMS91cGRhdGUudHh0CgoJIyByZWJvb3Rp
bmcgY2FtZXJhIHRvIG1ha2Ugc3VyZSBhbGwKCSMgdGhlIHNldHRpbmdzIHN0aWNrCglzaCAvbW50
L2NmZzEvc2NyaXB0cy9yZWJvb3RfY2FtZXJhLnNoCmZpCgojIGNsZWFuIGV4aXQKZXhpdCAwCgoA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZmlsZXMvcGhlbm9jYW1faXBf
dGFibGUuc2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAwMDA3NTUAMDAwMTc1MAAwMDAxNzUwADAwMDAwMDAy
NjEyADE0NjU3NTc2NjMxADAxNjQxMwAgMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAB1c3RhciAgAGtodWZrZW5zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa2h1Zmtl
bnMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjIS9iaW4vc2gKCiMtLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLQojIChjKSBLb2VuIEh1ZmtlbnMgZm9yIEJsdWVHcmVlbiBMYWJzIChCVikKIwojIFVuYXV0
aG9yaXplZCBjaGFuZ2VzIHRvIHRoaXMgc2NyaXB0IGFyZSBjb25zaWRlcmVkIGEgY29weXJpZ2h0
CiMgdmlvbGF0aW9uIGFuZCB3aWxsIGJlIHByb3NlY3V0ZWQuCiMKIy0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCgojIGhh
cmQgY29kZSBwYXRoIHdoaWNoIGFyZSBsb3N0IGluIHNvbWUgaW5zdGFuY2VzCiMgd2hlbiBjYWxs
aW5nIHRoZSBzY3JpcHQgdGhyb3VnaCBzc2ggClBBVEg9Ii91c3IvbG9jYWwvYmluOi91c3IvbG9j
YWwvc2JpbjovdXNyL2JpbjovdXNyL3NiaW46L2Jpbjovc2JpbiIKCiMgc29tZSBmZWVkYmFjayBv
biB0aGUgYWN0aW9uCmVjaG8gInVwbG9hZGluZyBJUCB0YWJsZSIKCiMgaG93IG1hbnkgc2VydmVy
cyBkbyB3ZSB1cGxvYWQgdG8KbnJzZXJ2ZXJzPWBhd2sgJ0VORCB7cHJpbnQgTlJ9JyAvbW50L2Nm
ZzEvc2VydmVyLnR4dGAKbnJzZXJ2ZXJzPWBhd2sgLXYgdmFyPSR7bnJzZXJ2ZXJzfSAnQkVHSU57
IG49MTsgd2hpbGUgKG4gPD0gdmFyICkgeyBwcmludCBuOyBuKys7IH0gfScgfCB0ciAnXG4nICcg
J2AKCiMgZ3JhYiB0aGUgbmFtZSwgZGF0ZSBhbmQgSVAgb2YgdGhlIGNhbWVyYQpEQVRFVElNRT1g
ZGF0ZWAKCiMgZ3JhYiBpbnRlcm5hbCBpcCBhZGRyZXNzCklQPWBpZmNvbmZpZyBldGgwIHwgYXdr
ICcvaW5ldCBhZGRyL3twcmludCBzdWJzdHIoJDIsNil9J2AKU0lURU5BTUU9YGF3ayAnTlI9PTEn
IC9tbnQvY2ZnMS9zZXR0aW5ncy50eHRgCgojIHVwZGF0ZSB0aGUgSVAgYW5kIHRpbWUgdmFyaWFi
bGVzCmNhdCAvbW50L2NmZzEvc2NyaXB0cy9zaXRlX2lwLmh0bWwgfCBzZWQgInN8REFURVRJTUV8
JERBVEVUSU1FfGciIHwgc2VkICJzfFNJVEVJUHwkSVB8ZyIgPiAvdmFyL3RtcC8ke1NJVEVOQU1F
fVxfaXAuaHRtbAoKIyBydW4gdGhlIHVwbG9hZCBzY3JpcHQgZm9yIHRoZSBpcCBkYXRhCiMgYW5k
IGZvciBhbGwgc2VydmVycwpmb3IgaSBpbiAkbnJzZXJ2ZXJzIDsKZG8KIFNFUlZFUj1gYXdrIC12
IHA9JGkgJ05SPT1wJyAvbW50L2NmZzEvc2VydmVyLnR4dGAgCgkKICMgdXBsb2FkIGltYWdlCiBl
Y2hvICJ1cGxvYWRpbmcgTklSIGltYWdlICR7aW1hZ2V9IgogZnRwcHV0ICR7U0VSVkVSfSAtdSAi
YW5vbnltb3VzIiAtcCAiYW5vbnltb3VzIiBkYXRhLyR7U0lURU5BTUV9LyR7U0lURU5BTUV9XF9p
cC5odG1sIC92YXIvdG1wLyR7U0lURU5BTUV9XF9pcC5odG1sCgpkb25lCgojIGNsZWFuIHVwCnJt
IC92YXIvdG1wLyR7U0lURU5BTUV9XF9pcC5odG1sCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmaWxlcy9waGVub2NhbV91cGxvYWQu
c2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAMDAwMDc3NQAwMDAxNzUwADAwMDE3NTAAMDAwMDAwMTcwMTAA
MTQ2NTQ3MjQ0NTIAMDE2MTExACAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAHVzdGFyICAAa2h1ZmtlbnMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABraHVma2VucwAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMhL2Jpbi9zaAoKIy0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
CiMgKGMpIEtvZW4gSHVma2VucyBmb3IgQmx1ZUdyZWVuIExhYnMgKEJWKQojCiMgVW5hdXRob3Jp
emVkIGNoYW5nZXMgdG8gdGhpcyBzY3JpcHQgYXJlIGNvbnNpZGVyZWQgYSBjb3B5cmlnaHQKIyB2
aW9sYXRpb24gYW5kIHdpbGwgYmUgcHJvc2VjdXRlZC4KIwojLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KCiMgaGFyZCBj
b2RlIHBhdGggd2hpY2ggYXJlIGxvc3QgaW4gc29tZSBpbnN0YW5jZXMKIyB3aGVuIGNhbGxpbmcg
dGhlIHNjcmlwdCB0aHJvdWdoIHNzaCAKUEFUSD0iL3Vzci9sb2NhbC9iaW46L3Vzci9sb2NhbC9z
YmluOi91c3IvYmluOi91c3Ivc2JpbjovYmluOi9zYmluIgoKIy0tLS0gZmVlZGJhY2sgb24gc3Rh
cnR1cCAtLS0KCmVjaG8gIiIKZWNobyAiU3RhcnRpbmcgaW1hZ2UgdXBsb2FkcyAuLi4gIgplY2hv
ICIiCgojLS0tLSBzdWJyb3V0aW5lcyAtLS0KCmNhcHR1cmUoKSB7CgogaW1hZ2U9JDEKIG1ldGFm
aWxlPSQyCiBkZWxheT0kMwogaXI9JDQKCiAjIFNldCB0aGUgaW1hZ2UgdG8gbm9uIElSIGkuZS4g
VklTCiAvdXNyL3NiaW4vc2V0X2lyLnNoICRpciA+L2Rldi9udWxsIDI+L2Rldi9udWxsCgogIyBh
ZGp1c3QgZXhwb3N1cmUKIHNsZWVwICRkZWxheQoKICMgZ3JhYiB0aGUgaW1hZ2UgZnJvbSB0aGUK
IHdnZXQgaHR0cDovLzEyNy4wLjAuMS9pbWFnZS5qcGcgLU8gJHtpbWFnZX0gPi9kZXYvbnVsbCAy
Pi9kZXYvbnVsbAoKICMgZ3JhYiBkYXRlIGFuZCB0aW1lIGZvciBgLm1ldGFgIGZpbGVzCiBNRVRB
REFURVRJTUU9YGRhdGUgLUlzZWNvbmRzYAoKICMgZ3JhYiB0aGUgZXhwb3N1cmUgdGltZSBhbmQg
YXBwZW5kIHRvIG1ldGEtZGF0YQogZXhwb3N1cmU9YC91c3Ivc2Jpbi9nZXRfZXhwIHwgY3V0IC1k
ICcgJyAtZjRgCgogIyBhZGp1c3QgbWV0YS1kYXRhIGZpbGUKIGNhdCAvdmFyL3RtcC9tZXRhZGF0
YS50eHQgPiAvdmFyL3RtcC8ke21ldGFmaWxlfQogZWNobyAiZXhwb3N1cmU9JHtleHBvc3VyZX0i
ID4+IC92YXIvdG1wLyR7bWV0YWZpbGV9CiBlY2hvICJpcl9lbmFibGU9JGlyIiA+PiAvdmFyL3Rt
cC8ke21ldGFmaWxlfQogZWNobyAiZGF0ZXRpbWVfb3JpZ2luYWw9XCIkTUVUQURBVEVUSU1FXCIi
ID4+IC92YXIvdG1wLyR7bWV0YWZpbGV9Cgp9CgojIC0tLS0tLS0tLS0tLS0tIFNFVFRJTkdTIC0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KCiMgcmVhZCBpbiBjb25m
aWd1cmF0aW9uIHNldHRpbmdzCiMgZ3JhYiBzaXRlbmFtZQpTSVRFTkFNRT1gYXdrICdOUj09MScg
L21udC9jZmcxL3NldHRpbmdzLnR4dGAKCiMgZ3JhYiB0aW1lIG9mZnNldCAvIGxvY2FsIHRpbWUg
em9uZQojIGFuZCBjb252ZXJ0ICsvLSB0byBhc2NpaQp0aW1lX29mZnNldD1gYXdrICdOUj09Micg
L21udC9jZmcxL3NldHRpbmdzLnR4dGAKU0lHTj1gZWNobyAke3RpbWVfb2Zmc2V0fSB8IGN1dCAt
YycxJ2AKCmlmIFsgIiRTSUdOIiA9ICIrIiBdOyB0aGVuCiB0aW1lX29mZnNldD1gZWNobyAiJHt0
aW1lX29mZnNldH0iIHwgc2VkICdzLysvJTJCL2cnYAplbHNlCiB0aW1lX29mZnNldD1gZWNobyAi
JHt0aW1lX29mZnNldH0iIHwgc2VkICdzLy0vJTJEL2cnYApmaQoKIyBzZXQgY2FtZXJhIG1vZGVs
IG5hbWUKbW9kZWw9Ik5ldENhbSBMaXZlMiIKCiMgaG93IG1hbnkgc2VydmVycyBkbyB3ZSB1cGxv
YWQgdG8KbnJzZXJ2ZXJzPWBhd2sgJ0VORCB7cHJpbnQgTlJ9JyAvbW50L2NmZzEvc2VydmVyLnR4
dGAKbnJzZXJ2ZXJzPWBhd2sgLXYgdmFyPSR7bnJzZXJ2ZXJzfSAnQkVHSU57IG49MTsgd2hpbGUg
KG4gPD0gdmFyICkgeyBwcmludCBuOyBuKys7IH0gfScgfCB0ciAnXG4nICcgJ2AKCiMgZ3JhYiBw
YXNzd29yZApwYXNzPWBhd2sgJ05SPT0xJyAvbW50L2NmZzEvLnBhc3N3b3JkYAoKIyBNb3ZlIGlu
dG8gdGVtcG9yYXJ5IGRpcmVjdG9yeQojIHdoaWNoIHJlc2lkZXMgaW4gUkFNLCBub3QgdG8KIyB3
ZWFyIG91dCBvdGhlciBwZXJtYW5lbnQgbWVtb3J5CmNkIC92YXIvdG1wCgojIHNldHMgdGhlIGRl
bGF5IGJldHdlZW4gdGhlCiMgUkdCIGFuZCBJUiBpbWFnZSBhY3F1aXNpdGlvbnMKREVMQVk9MzAK
CiMgZ3JhYiBkYXRlIC0ga2VlcCBmaXhlZCBmb3IgUkdCIGFuZCBJUiB1cGxvYWRzCkRBVEU9YGRh
dGUgKyIlYSAlYiAlZCAlWSAlSDolTTolUyJgCgojIGdyYXAgZGF0ZSBhbmQgdGltZSBzdHJpbmcg
dG8gYmUgaW5zZXJ0ZWQgaW50byB0aGUKIyBmdHAgc2NyaXB0cyAtIHRoaXMgY29vcmRpbmF0ZXMg
dGhlIHRpbWUgc3RhbXBzCiMgYmV0d2VlbiB0aGUgUkdCIGFuZCBJUiBpbWFnZXMgKG90aGVyd2lz
ZSB0aGVyZSBpcyBhCiMgc2xpZ2h0IG9mZnNldCBkdWUgdG8gdGhlIHRpbWUgbmVlZGVkIHRvIGFk
anVzdCBleHBvc3VyZQpEQVRFVElNRVNUUklORz1gZGF0ZSArIiVZXyVtXyVkXyVIJU0lUyJgCgoj
IGdyYWIgbWV0YWRhdGEgdXNpbmcgdGhlIG1ldGFkYXRhIGZ1bmN0aW9uCiMgZ3JhYiB0aGUgTUFD
IGFkZHJlc3MKbWFjX2FkZHI9YGlmY29uZmlnIGV0aDAgfCBncmVwICdIV2FkZHInIHwgYXdrICd7
cHJpbnQgJDV9JyB8IHNlZCAncy86Ly9nJ2AKCiMgZ3JhYiBpbnRlcm5hbCBpcCBhZGRyZXNzCmlw
X2FkZHI9YGlmY29uZmlnIGV0aDAgfCBhd2sgJy9pbmV0IGFkZHIve3ByaW50IHN1YnN0cigkMiw2
KX0nYAoKIyBncmFiIGV4dGVybmFsIGlwIGFkZHJlc3MgaWYgdGhlcmUgaXMgYW4gZXh0ZXJuYWwg
Y29ubmVjdGlvbgojIGZpcnN0IHRlc3QgdGhlIGNvbm5lY3Rpb24gdG8gdGhlIGdvb2dsZSBuYW1l
IHNlcnZlcgpjb25uZWN0aW9uPWBwaW5nIC1xIC1jIDEgOC44LjguOCA+IC9kZXYvbnVsbCAmJiBl
Y2hvIG9rIHx8IGVjaG8gZXJyb3JgCgojIGdyYWIgdGltZSB6b25lCnR6PWBjYXQgL3Zhci9UWmAK
CiMgZ2V0IFNEIGNhcmQgcHJlc2VuY2UKU0RDQVJEPWBkZiB8IGdyZXAgIm1tYyIgfCB3YyAtbGAK
CiMgYmFja3VwIHRvIFNEIGNhcmQgd2hlbiBpbnNlcnRlZAojIHJ1bnMgb24gcGhlbm9jYW0gdXBs
b2FkIHJhdGhlciB0aGFuIGluc3RhbGwKIyB0byBhbGxvdyBob3Qtc3dhcHBpbmcgb2YgY2FyZHMK
aWYgWyAiJFNEQ0FSRCIgLWVxIDEgXTsgdGhlbgogCiAjIGNyZWF0ZSBiYWNrdXAgZGlyZWN0b3J5
CiBta2RpciAtcCAvbW50L21tYy9waGVub2NhbV9iYWNrdXAvCiAKZmkKCiMgLS0tLS0tLS0tLS0t
LS0gU0VUIEZJWEVEIERBVEUgVElNRSBIRUFERVIgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQoK
IyBvdmVybGF5IHRleHQKb3ZlcmxheV90ZXh0PWBlY2hvICIke1NJVEVOQU1FfSAtICR7bW9kZWx9
IC0gJHtEQVRFfSAtIEdNVCR7dGltZV9vZmZzZXR9IiB8IHNlZCAncy8gLyUyMC9nJ2AKCQojIGZv
ciBub3cgZGlzYWJsZSB0aGUgb3ZlcmxheQp3Z2V0IGh0dHA6Ly9hZG1pbjoke3Bhc3N9QDEyNy4w
LjAuMS92Yi5odG0/b3ZlcmxheXRleHQxPSR7b3ZlcmxheV90ZXh0fSA+L2Rldi9udWxsIDI+L2Rl
di9udWxsCgojIGNsZWFuIHVwIGRldHJpdHVzCnJtIHZiKgoKIyAtLS0tLS0tLS0tLS0tLSBTRVQg
RklYRUQgTUVUQS1EQVRBIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KCiMgY3JlYXRl
IGJhc2UgbWV0YS1kYXRhIGZpbGUgZnJvbSBjb25maWd1cmF0aW9uIHNldHRpbmdzCiMgYW5kIHRo
ZSBmaXhlZCBwYXJhbWV0ZXJzCmVjaG8gIm1vZGVsPU5ldENhbSBMaXZlMiIgPiAvdmFyL3RtcC9t
ZXRhZGF0YS50eHQKL21udC9jZmcxL3NjcmlwdHMvY2hscyA+PiAvdmFyL3RtcC9tZXRhZGF0YS50
eHQKZWNobyAiaXBfYWRkcj0kaXBfYWRkciIgPj4gL3Zhci90bXAvbWV0YWRhdGEudHh0CmVjaG8g
Im1hY19hZGRyPSRtYWNfYWRkciIgPj4gL3Zhci90bXAvbWV0YWRhdGEudHh0CmVjaG8gInRpbWVf
em9uZT0kdHoiID4+IC92YXIvdG1wL21ldGFkYXRhLnR4dAplY2hvICJvdmVybGF5X3RleHQ9JG92
ZXJsYXlfdGV4dCIgPj4gL3Zhci90bXAvbWV0YWRhdGEudHh0CgojIGNvbG91ciBiYWxhbmNlIHNl
dHRpbmdzCnJlZD1gYXdrICdOUj09NycgL21udC9jZmcxL3NldHRpbmdzLnR4dGAKZ3JlZW49YGF3
ayAnTlI9PTgnIC9tbnQvY2ZnMS9zZXR0aW5ncy50eHRgCmJsdWU9YGF3ayAnTlI9PTknIC9tbnQv
Y2ZnMS9zZXR0aW5ncy50eHRgIApicmlnaHRuZXNzPWBhd2sgJ05SPT0xMCcgL21udC9jZmcxL3Nl
dHRpbmdzLnR4dGAKc2hhcnBuZXNzPWBhd2sgJ05SPT0xMScgL21udC9jZmcxL3NldHRpbmdzLnR4
dGAKaHVlPWBhd2sgJ05SPT0xMicgL21udC9jZmcxL3NldHRpbmdzLnR4dGAKY29udHJhc3Q9YGF3
ayAnTlI9PTEzJyAvbW50L2NmZzEvc2V0dGluZ3MudHh0YAkgCnNhdHVyYXRpb249YGF3ayAnTlI9
PTE0JyAvbW50L2NmZzEvc2V0dGluZ3MudHh0YApibGM9YGF3ayAnTlI9PTE1JyAvbW50L2NmZzEv
c2V0dGluZ3MudHh0YAoKZWNobyAicmVkPSRyZWQiID4+IC92YXIvdG1wL21ldGFkYXRhLnR4dApl
Y2hvICJncmVlbj0kZ3JlZW4iID4+IC92YXIvdG1wL21ldGFkYXRhLnR4dAplY2hvICJibHVlPSRi
bHVlIiA+PiAvdmFyL3RtcC9tZXRhZGF0YS50eHQKZWNobyAiYnJpZ2h0bmVzcz0kYnJpZ2h0bmVz
cyIgPj4gL3Zhci90bXAvbWV0YWRhdGEudHh0CmVjaG8gImNvbnRyYXN0PSRjb250cmFzdCIgPj4g
L3Zhci90bXAvbWV0YWRhdGEudHh0CmVjaG8gImh1ZT0kaHVlIiA+PiAvdmFyL3RtcC9tZXRhZGF0
YS50eHQKZWNobyAic2hhcnBuZXNzPSRzaGFycG5lc3MiID4+IC92YXIvdG1wL21ldGFkYXRhLnR4
dAplY2hvICJzYXR1cmF0aW9uPSRzYXR1cmF0aW9uIiA+PiAvdmFyL3RtcC9tZXRhZGF0YS50eHQK
ZWNobyAiYmFja2xpZ2h0PSRibGMiID4+IC92YXIvdG1wL21ldGFkYXRhLnR4dAoKIyAtLS0tLS0t
LS0tLS0tLSBVUExPQUQgREFUQSAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tCgojIHdlIHVzZSB0d28gc3RhdGVzIHRvIGluZGljYXRlIFZJUyAoMCkgYW5kIE5JUiAoMSkg
c3RhdGVzCiMgYW5kIHVzZSBhIGZvciBsb29wIHRvIGN5Y2xlIHRocm91Z2ggdGhlc2Ugc3RhdGVz
IGFuZAojIHVwbG9hZCB0aGUgZGF0YQpzdGF0ZXM9IjAgMSIKCmZvciBzdGF0ZSBpbiAkc3RhdGVz
OwpkbwoKIGlmIFsgIiRzdGF0ZSIgLWVxIDAgXTsgdGhlbgoKICAjIGNyZWF0ZSBWSVMgZmlsZW5h
bWVzCiAgbWV0YWZpbGU9YGVjaG8gJHtTSVRFTkFNRX1fJHtEQVRFVElNRVNUUklOR30ubWV0YWAK
ICBpbWFnZT1gZWNobyAke1NJVEVOQU1FfV8ke0RBVEVUSU1FU1RSSU5HfS5qcGdgCiAgY2FwdHVy
ZSAkaW1hZ2UgJG1ldGFmaWxlICRERUxBWSAwCgogZWxzZQoKICAjIGNyZWF0ZSBOSVIgZmlsZW5h
bWVzCiAgbWV0YWZpbGU9YGVjaG8gJHtTSVRFTkFNRX1fSVJfJHtEQVRFVElNRVNUUklOR30ubWV0
YWAKICBpbWFnZT1gZWNobyAke1NJVEVOQU1FfV9JUl8ke0RBVEVUSU1FU1RSSU5HfS5qcGdgCiAg
Y2FwdHVyZSAkaW1hZ2UgJG1ldGFmaWxlICRERUxBWSAxCiAKIGZpCgogIyBydW4gdGhlIHVwbG9h
ZCBzY3JpcHQgZm9yIHRoZSBpcCBkYXRhCiAjIGFuZCBmb3IgYWxsIHNlcnZlcnMKIGZvciBpIGlu
ICRucnNlcnZlcnM7CiBkbwogIFNFUlZFUj1gYXdrIC12IHA9JGkgJ05SPT1wJyAvbW50L2NmZzEv
c2VydmVyLnR4dGAKIAogIGVjaG8gInVwbG9hZGluZyB0bzogJHtTRVJWRVJ9IgogCiAgIyBpZiBr
ZXkgZmlsZSBleGlzdHMgdXNlIFNGVFAKICBpZiBbIC1mICIvbW50L2NmZzEvcGhlbm9jYW1fa2V5
IiBdOyB0aGVuCiAgIGVjaG8gInVzaW5nIHNGVFAiCiAgCiAgIGVjaG8gIlBVVCAke2ltYWdlfSBk
YXRhLyR7U0lURU5BTUV9LyR7aW1hZ2V9IiA+IGJhdGNoZmlsZQogICBlY2hvICJQVVQgJHttZXRh
ZmlsZX0gZGF0YS8ke1NJVEVOQU1FfS8ke21ldGFmaWxlfSIgPj4gYmF0Y2hmaWxlCiAgCiAgICMg
dXBsb2FkIHRoZSBkYXRhCiAgIGVjaG8gIlVwbG9hZGluZyAoc3RhdGU6ICR7c3RhdGV9KSIKICAg
ZWNobyAiIC0gaW1hZ2UgZmlsZTogJHtpbWFnZX0iCiAgIGVjaG8gIiAtIG1ldGEtZGF0YSBmaWxl
OiAke21ldGFmaWxlfSIKICAgc2Z0cCAtYiBiYXRjaGZpbGUgLWkgIi9tbnQvY2ZnMS9waGVub2Nh
bV9rZXkiIHBoZW5vc2Z0cEAke1NFUlZFUn0gPi9kZXYvbnVsbCAyPi9kZXYvbnVsbAogICAKICAg
IyByZW1vdmUgYmF0Y2ggZmlsZQogICBybSBiYXRjaGZpbGUKICAgCiAgZWxzZQogICBlY2hvICJV
c2luZyBGVFAgW2NoZWNrIHlvdXIgaW5zdGFsbCB0byB1c2Ugc0ZUUF0iCiAgCiAgICMgdXBsb2Fk
IGltYWdlCiAgIGVjaG8gIlVwbG9hZGluZyAoc3RhdGU6ICR7c3RhdGV9KSIKICAgZWNobyAiIC0g
aW1hZ2UgZmlsZTogJHtpbWFnZX0iCiAgIGZ0cHB1dCAke1NFUlZFUn0gLS11c2VybmFtZSBhbm9u
eW1vdXMgLS1wYXNzd29yZCBhbm9ueW1vdXMgIGRhdGEvJHtTSVRFTkFNRX0vJHtpbWFnZX0gJHtp
bWFnZX0gPi9kZXYvbnVsbCAyPi9kZXYvbnVsbAoJCiAgIGVjaG8gIiAtIG1ldGEtZGF0YSBmaWxl
OiAke21ldGFmaWxlfSIKICAgZnRwcHV0ICR7U0VSVkVSfSAtLXVzZXJuYW1lIGFub255bW91cyAt
LXBhc3N3b3JkIGFub255bW91cyAgZGF0YS8ke1NJVEVOQU1FfS8ke21ldGFmaWxlfSAke21ldGFm
aWxlfSA+L2Rldi9udWxsIDI+L2Rldi9udWxsCgogIGZpCiBkb25lCgogIyBiYWNrdXAgdG8gU0Qg
Y2FyZCB3aGVuIGluc2VydGVkCiBpZiBbICIkU0RDQVJEIiAtZXEgMSBdOyB0aGVuIAogIGNwICR7
aW1hZ2V9IC9tbnQvbW1jL3BoZW5vY2FtX2JhY2t1cC8ke2ltYWdlfQogIGNwICR7bWV0YWZpbGV9
IC9tbnQvbW1jL3BoZW5vY2FtX2JhY2t1cC8ke21ldGFmaWxlfQogZmkKCiAjIGNsZWFuIHVwIGZp
bGVzCiBybSAqLmpwZwogcm0gKi5tZXRhCgpkb25lCgojIFJlc2V0IHRvIFZJUyBhcyBkZWZhdWx0
Ci91c3Ivc2Jpbi9zZXRfaXIuc2ggMAoKIy0tLS0tLS0tLS0tLS0tIFJFU0VUIE5PUk1BTCBIRUFE
RVIgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KCiMgb3ZlcmxheSB0ZXh0Cm92ZXJs
YXlfdGV4dD1gZWNobyAiJHtTSVRFTkFNRX0gLSAke21vZGVsfSAtICVhICViICVkICVZICVIOiVN
OiVTIC0gR01UJHt0aW1lX29mZnNldH0iIHwgc2VkICdzLyAvJTIwL2cnYAoJCiMgZm9yIG5vdyBk
aXNhYmxlIHRoZSBvdmVybGF5CndnZXQgaHR0cDovL2FkbWluOiR7cGFzc31AMTI3LjAuMC4xL3Zi
Lmh0bT9vdmVybGF5dGV4dDE9JHtvdmVybGF5X3RleHR9ID4vZGV2L251bGwgMj4vZGV2L251bGwK
CiMgY2xlYW4gdXAgZGV0cml0dXMKcm0gdmIqCgojLS0tLS0tLSBGRUVEQkFDSyBPTiBBQ1RJVklU
WSAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KaWYgWyAhIC1mICIvdmFy
L3RtcC9pbWFnZV9sb2cudHh0IiBdOyB0aGVuCiB0b3VjaCAvdmFyL3RtcC9pbWFnZV9sb2cudHh0
CiBjaG1vZCBhK3J3IC92YXIvdG1wL2ltYWdlX2xvZy50eHQKZmkKCmVjaG8gImxhc3QgdXBsb2Fk
cyBhdDoiID4+IC92YXIvdG1wL2ltYWdlX2xvZy50eHQKZWNobyAkREFURSA+PiAvdmFyL3RtcC9p
bWFnZV9sb2cudHh0CnRhaWwgL3Zhci90bXAvaW1hZ2VfbG9nLnR4dAoKIy0tLS0tLS0gRklMRSBQ
RVJNSVNTSU9OUyBBTkQgQ0xFQU5VUCAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCnJt
IC1mIC92YXIvdG1wL21ldGFkYXRhLnR4dAoKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAZmlsZXMvcmVib290X2NhbWVyYS5zaAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAADAwMDA2NjQAMDAwMTc1MAAwMDAxNzUwADAwMDAwMDAxNTEwADE0NjU3NjA2NjIzADAxNTU1
MgAgMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1c3RhciAgAGto
dWZrZW5zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa2h1ZmtlbnMAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAjIS9iaW4vc2gKCiMtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQojIChjKSBLb2VuIEh1Zmtl
bnMgZm9yIEJsdWVHcmVlbiBMYWJzIChCVikKIwojIFVuYXV0aG9yaXplZCBjaGFuZ2VzIHRvIHRo
aXMgc2NyaXB0IGFyZSBjb25zaWRlcmVkIGEgY29weXJpZ2h0CiMgdmlvbGF0aW9uIGFuZCB3aWxs
IGJlIHByb3NlY3V0ZWQuCiMKIy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCgojIGhhcmQgY29kZSBwYXRoIHdoaWNoIGFy
ZSBsb3N0IGluIHNvbWUgaW5zdGFuY2VzCiMgd2hlbiBjYWxsaW5nIHRoZSBzY3JpcHQgdGhyb3Vn
aCBzc2ggClBBVEg9Ii91c3IvbG9jYWwvYmluOi91c3IvbG9jYWwvc2JpbjovdXNyL2JpbjovdXNy
L3NiaW46L2Jpbjovc2JpbiIKCiMgZ3JhYiBwYXNzd29yZApwYXNzPWBhd2sgJ05SPT0xJyAvbW50
L2NmZzEvLnBhc3N3b3JkYAoKIyBtb3ZlIGludG8gdGVtcG9yYXJ5IGRpcmVjdG9yeQpjZCAvdmFy
L3RtcAoKIyBzbGVlcCAzMCBzZWNvbmRzIGZvciBsYXN0CiMgY29tbWFuZCB0byBmaW5pc2ggKGlm
IGFueSBzaG91bGQgYmUgcnVubmluZykKc2xlZXAgMzAKCiMgdGhlbiByZWJvb3QKd2dldCBodHRw
Oi8vYWRtaW46JHtwYXNzfUAxMjcuMC4wLjEvdmIuaHRtP2lwY2FtcmVzdGFydGNtZCAmPi9kZXYv
bnVsbAoKIyBkb24ndCBleGl0IGNsZWFubHkgd2hlbiB0aGUgcmVib290IGNvbW1hbmQgZG9lc24n
dCBzdGljawojIHNob3VsZCB0cmlnZ2VyIGEgd2FybmluZyBtZXNzYWdlCnNsZWVwIDYwCmV4aXQg
MQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAZmlsZXMvc2l0ZV9pcC5odG1sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
ADAwMDA2NjQAMDAwMTc1MAAwMDAxNzUwADAwMDAwMDAwNTYwADE0NTM2NTUyNTAwADAxNDczMAAg
MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1c3RhciAgAGtodWZr
ZW5zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa2h1ZmtlbnMAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA8IURPQ1RZUEUgaHRtbCBQVUJMSUMgIi0vL1czQy8vRFREIEhUTUwgNC4w
IFRyYW5zaXRpb25hbC8vRU4iPgo8aHRtbD4KPGhlYWQ+CjxtZXRhIGh0dHAtZXF1aXY9IkNvbnRl
bnQtVHlwZSIgY29udGVudD0idGV4dC9odG1sOyBjaGFyc2V0PWlzby04ODU5LTEiPgo8dGl0bGU+
TmV0Q2FtU0MgSVAgQWRkcmVzczwvdGl0bGU+CjwvaGVhZD4KPGJvZHk+ClRpbWUgb2YgTGFzdCBJ
UCBVcGxvYWQ6IERBVEVUSU1FPGJyPgpJUCBBZGRyZXNzOiBTSVRFSVAKJmJ1bGw7IDxhIGhyZWY9
Imh0dHA6Ly9TSVRFSVAvIj5WaWV3PC9hPgomYnVsbDsgPGEgaHJlZj0iaHR0cDovL1NJVEVJUC9h
ZG1pbi5jZ2kiPkNvbmZpZ3VyZTwvYT4KPC9ib2R5Pgo8L2h0bWw+CgAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
